#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xama.JTPorts.RippleBackground.Resource", IsApplication=false)]

namespace Xama.JTPorts.RippleBackground
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public static int rb_duration = 2130771972;
			
			// aapt resource value: 0x7f010003
			public static int rb_radius = 2130771971;
			
			// aapt resource value: 0x7f010005
			public static int rb_rippleAmount = 2130771973;
			
			// aapt resource value: 0x7f010001
			public static int rb_rippleColour = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int rb_rippleOnClick = 2130771968;
			
			// aapt resource value: 0x7f010006
			public static int rb_scale = 2130771974;
			
			// aapt resource value: 0x7f010002
			public static int rb_strokeWidth = 2130771970;
			
			// aapt resource value: 0x7f010007
			public static int rb_type = 2130771975;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f020001
			public static int rippleRadius = 2130837505;
			
			// aapt resource value: 0x7f020000
			public static int rippleStrokeWidth = 2130837504;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public static int fillRipple = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int strokeRipple = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public static int app_name = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RippleBackground = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 4
			public static int RippleBackground_rb_duration = 4;
			
			// aapt resource value: 3
			public static int RippleBackground_rb_radius = 3;
			
			// aapt resource value: 5
			public static int RippleBackground_rb_rippleAmount = 5;
			
			// aapt resource value: 1
			public static int RippleBackground_rb_rippleColour = 1;
			
			// aapt resource value: 0
			public static int RippleBackground_rb_rippleOnClick = 0;
			
			// aapt resource value: 6
			public static int RippleBackground_rb_scale = 6;
			
			// aapt resource value: 2
			public static int RippleBackground_rb_strokeWidth = 2;
			
			// aapt resource value: 7
			public static int RippleBackground_rb_type = 7;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
